### ISSUE TITLE
B1.2023-09-26

### ISSUE THREAD

**Issue by Preference-Kim** [Preference-Kim/ultralytics#1]
## B1.1 Warning

/miniconda3/envs/yv8/lib/python3.11/site-packages/torch/functional.py:504: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at /opt/conda/conda-bld/pytorch_1682343995622/work/aten/src/ATen/native/TensorShape.cpp:3483.)

## B1.2 Runtime Error

  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
Traceback (most recent call last):
  File "blueprint.py", line 58, in <module>
    frame = r.gen_sklt(mix=ismix, color='seg')
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Ultralytics/mylibrary/myengine/myresults.py", line 80, in gen_sklt
    self.kpts(im[0], kpts, self.orig_shape, radius=kpt_radius)
  File "/Ultralytics/mylibrary/myengine/myresults.py", line 127, in kpts
    img = self.draw_line(img, pos1, pos2, self.limb_color[i], thickness=2)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Ultralytics/mylibrary/myengine/myresults.py", line 206, in draw_line
    expanded_x_coords = x_coords.unsqueeze(0) + x_grid
                        ~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~
RuntimeError: The size of tensor a (19133) must match the size of tensor b (3) at non-singleton dimension 1

## B1.3 Attribute Error

Exception ignored in: <generator object PosePredictor.pipe_stream_inference at 0x7fb52da0a320>
Traceback (most recent call last):
  File "~/miniconda3/envs/yv8/lib/python3.11/site-packages/torch/utils/_contextlib.py", line 44, in generator_context
  File "~/miniconda3/envs/yv8/lib/python3.11/site-packages/torch/autograd/grad_mode.py", line 223, in clone
  File "~/miniconda3/envs/yv8/lib/python3.11/site-packages/torch/autograd/grad_mode.py", line 209, in __init__
AttributeError: 'NoneType' object has no attribute 'is_scripting'

**Comment by Preference-Kim** [comment]
Have been fixed on commit https://github.com/Preference-Kim/ultralytics/commit/b34f92ad724dffcd1835c62e7ebd168898ad6128
